MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224_22k
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "/home/VTUNet/vtunet/pretrained_ckpt/swin_tiny_patch4_window7_224_22k.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 72
    DEPTHS: [ 2, 2, 2, 1 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
